name: CI/CD workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js and pnpm
      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Run linting
      - name: Run lint
        run: pnpm run lint

      # Run tests
      - name: Run tests
        run: pnpm run test

      # Build the project
      - name: Build the project
        run: pnpm run build


      - name: Copy README.md
        run: cp README.md dist

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
